# -*- coding: utf-8 -*-
"""1.l6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mm2xwQcN1JOMT30719MS2Qy2DYXZFwet
"""

import matplotlib.pyplot as plt
import numpy as np
import random
import math
import kolizja as kolizja1
import przes

tab=[]

for q in range (100):
  a=random.uniform(-14.5, 14.5)
  b=random.uniform(-14.5, 14.5)
  r=0.5
  x=np.arange(a-r,a+r,0.01)
  y=[]
  tab.append([])
  tab[q].append(a)
  tab[q].append(b)
  for i in x:
    y.append(abs(r**2-(i-a)**2)**0.5+b)
  for i in x[::-1]:
    y.append(-(abs(r**2-(i-a)**2)**0.5)+b)
  x=list(x)+list(x[::-1])
  plt.plot(x,y)

plt.show()
#print(tab)

for k in range(100):
  c=0
  for i in range (100):
      for j in range (100):
        if kolizja1.kolizja(tab[i][0],tab[i][1],tab[j][0],tab[j][1]):
          c=c+1
          q=tab[i][0]-tab[j][0]
          p=tab[i][1]-tab[j][1]
          if p==0.0:
            s=[(1-q)/2,0]
            s2=[(q-1)/2,0]
          if q==0.0:
            s=[0,(1-p)/2]
            s2=[0,(p-1)/2]
          if q>p and q!=0.0:
            s=[1,p/q/2]
            s2=[-1,-p/2/q]
          if (q<p or q==p) and p!=0.0:
            s=[q/p/2,1]
            s2=[-q/p/2,-1]
          tab[i]=przes.przes(tab[i],s)
          tab[j]=przes.przes(tab[j],s2)
      for i in range (100):
        if tab[i][0]>14.5: tab[i][0]=14.5
        if tab[i][0]<-14.5: tab[i][0]=-14.5
        if tab[i][1]>14.5: tab[i][1]=14.5
        if tab[i][1]<-14.5: tab[i][1]=-14.5
  print(c)
  if c==100:
    break

for q in range (100):
  a=tab[q][0]
  b=tab[q][1]
  r=0.5
  x=np.arange(a-r,a+r,0.01)
  y=[]
  for i in x:
    y.append(abs(r**2-(i-a)**2)**0.5+b)
  for i in x[::-1]:
    y.append(-(abs(r**2-(i-a)**2)**0.5)+b)
  x=list(x)+list(x[::-1])
  plt.plot(x,y)

plt.show()
#print(tab)

#print(k)